### ISSUE TITLE
Graph generation dependencies for campaigns

### ISSUE THREAD

**Issue by ThomasVandermotten** [open-s4c/benchkit#13]
When directly executing the `generate_graph` function on a campaign(not a suite), the necessary dependencies: `pandas matplotlib seaborn` are not automatically added.

Error occured on: `campaign.generate_graph(
        plot_name="scatterplot",
        x="nb_threads",
        y="counter",
        #hue="clarity",
    )`

Stacktrace:
```Traceback (most recent call last):
  File "/home/pi/Documents/benchkit/benchkit/lwchart.py", line 158, in generate_chart_from_single_csv
    df = _read_csv(csv_pathname=csv_pathname)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/benchkit/benchkit/lwchart.py", line 105, in _read_csv
    return pd.read_csv(
           ^^
NameError: name 'pd' is not defined. Did you mean: 'id'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/benchkit/examples/counter/bench.py", line 252, in <module>
    campaign.generate_graph(
  File "/home/pi/Documents/benchkit/benchkit/campaign.py", line 242, in generate_graph
    generate_chart_from_single_csv(
  File "/home/pi/Documents/benchkit/benchkit/lwchart.py", line 159, in generate_chart_from_single_csv
    except pd.errors.EmptyDataError:
           ^^
NameError: name 'pd' is not defined. Did you mean: 'id'?```

**Comment by apaolillo** [comment]
Normally, when the dependencies are not there, lwchart should skip the graph generation. You hit a bug. I'm going to investigate.
