### ISSUE TITLE
Path of terminal does not seem to be available.

### ISSUE THREAD

**Issue by matsvanmolle** [open-s4c/benchkit#39]
When making a run command that includes a path variable or location of a program i.e. java benchkit returns an error.

`run_command = ["java", " --version]`  or `run_command = ["usr/bin/java", " --version]`

```
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
[INFO] Total number of runs: 2
[INFO] Expected duration: 10
[RUN] uname -a
[OUT]
Linux raspberrypi 6.6.22-v8+ #1 SMP PREEMPT Wed Mar 27 10:22:28 UTC 2024 aarch64 GNU/Linux
[INFO] Run  1/2, current campaign expected remaining time: ~10 seconds, i.e. ~0:00:10
[INFO] Full campaign suite estimated remaining time: ~10 seconds, i.e. ~0:00:10
[CD] .
[RUN] java --version
Traceback (most recent call last):
  File "/home/pi/Documents/benchkit/examples/volano/kit/benchcopy.py", line 275, in <module>
    campaign.run()
  File "/home/pi/Documents/benchkit/benchkit/campaign.py", line 197, in run
    self.campaign_run(other_campaigns_seconds=0, barrier=None)
  File "/home/pi/Documents/benchkit/benchkit/campaign.py", line 187, in campaign_run
    self._benchmark.run(
  File "/home/pi/Documents/benchkit/benchkit/benchmark.py", line 590, in run
    self._run_single_run(
  File "/home/pi/Documents/benchkit/benchkit/benchmark.py", line 1002, in _run_single_run
    single_run_return = self.single_run(
                        ^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/benchkit/examples/volano/kit/benchcopy.py", line 157, in single_run
    output = self.run_bench_command(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/benchkit/benchkit/benchmark.py", line 739, in run_bench_command
    output = self.platform.comm.shell(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/benchkit/benchkit/communication/__init__.py", line 464, in shell
    return shell_out(
           ^^^^^^^^^^
  File "/home/pi/Documents/benchkit/benchkit/shell/shell.py", line 193, in shell_out
    output = subprocess.check_output(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java --version'
```

**Comment by apaolillo** [comment]
@matsvanmolle that's strange. Could you provide a minimal python script that triggers the issue?
That would help debugging and understanding the issue.

**Comment by matsvanmolle** [comment]
@apaolillo  I think that it was a fault in my setup and not a bug in benchkit. Hower if you want to try it you can simply change the volano campaign. Instead of running with the shell script run it with directly calling java. Iirc it would also give an error but not the same one. If you would like I can also run it and give you the error.

**Comment by matsvanmolle** [comment]
@apaolillo After testing it seems like the issue was on my side and only occurred with my setup. I'll close the issue. However I'll create a PR for the volcano bench as it does no longer need the shell script and there are some typos in the readme.
