### ISSUE TITLE
issue when space in name package

### ISSUE THREAD

**Issue by MilanaAmighiVUB** [open-s4c/benchkit#9]
I have created package with name on it and I have the following issue:

milan@milan-HP-EliteBook-860-16-inch-G10-Notebook-PC:~/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench$ . ./venv/bin/activate
(venv) milan@milan-HP-EliteBook-860-16-inch-G10-Notebook-PC:~/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench$ ./campaign_leveldb.py
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
Campaign  1:       36 runs -          108 seconds - 0:01:48
----------------------------------------------------------------
Total:             36 runs -          108 seconds - 0:01:48
----------------------------------------------------------------
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
[WARNING] Host machine not registered with hostname, and deephierarchy module not found. Defaulting to generic platform.
[CD] /home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb/build-milan-HP-EliteBook-860-16-inch-G10-Notebook-PC
[RUN] cmake -DCMAKE_BUILD_TYPE=Release /home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb
CMake Error: The source directory "/home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb/build-milan-HP-EliteBook-860-16-inch-G10-Notebook-PC/analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "/home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/./campaign_leveldb.py", line 50, in <module>
    main()
  File "/home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/./campaign_leveldb.py", line 38, in main
    suite.run_suite()
  File "/home/milan/Performance analysis/TP4/benchkit-main/benchkit/campaign.py", line 310, in run_suite
    campaign.campaign_run(other_campaigns_seconds=remaining_seconds, barrier=None)
  File "/home/milan/Performance analysis/TP4/benchkit-main/benchkit/campaign.py", line 187, in campaign_run
    self._benchmark.run(
  File "/home/milan/Performance analysis/TP4/benchkit-main/benchkit/benchmark.py", line 534, in run
    prebuild_seconds = self.prebuild_bench(
  File "/home/milan/Performance analysis/TP4/benchkit-main/examples/leveldb/kit/leveldb.py", line 124, in prebuild_bench
    self.platform.comm.shell(
  File "/home/milan/Performance analysis/TP4/benchkit-main/benchkit/communication/__init__.py", line 464, in shell
    return shell_out(
  File "/home/milan/Performance analysis/TP4/benchkit-main/benchkit/shell/shell.py", line 175, in shell_out
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '/home/milan/Performance', 'analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb']' returned non-zero exit status 1.

That is the path that is creating:

milan@milan-HP-EliteBook-860-16-inch-G10-Notebook-PC:~/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench$ ls "/home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb/build-milan-HP-EliteBook-860-16-inch-G10-Notebook-PC/analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb"
ls: cannot access '/home/milan/Performance analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb/build-milan-HP-EliteBook-860-16-inch-G10-Notebook-PC/analysis/TP4/benchkit-main/tutorials/leveldb-bench/deps/leveldb': No such file or directory

**Comment by apaolillo** [comment]
@aaronbog could you take the issues of paths containing spaces into account in your shell command refactoring? I think the solutions we discussed could handle it nicely.
